### ISSUE TITLE
Using back/forward buttons on web, break various 'back' buttons in the app

### ISSUE THREAD

**Issue by esDotDev** [gskinnerTeam/flutter-wonderous-app#113]
The app often pushes routes on top of others, and relies on a call to 'pop` to return to the previous page. 

When using the browsers back/forward buttons the navigation stack is flattened, meaning any subsequent calls to `pop` remove the current route displaying only a white screen underneath. 

https://github.com/gskinnerTeam/flutter-wonderous-app/assets/736973/c02b368a-a9e1-4f6f-bd9c-105f84c2c864

We can potentially use the `canPop` API to mitigate this, but it seems like that would require passing in the previous path to any views that currently contain an internal back button, likely as a url param so it is preserved.
```[tasklist]
### Tasks
- [ ] Check whether there is an existing solution that GoRouter users rely on for this use case
- [ ] If not, create a simple spike illustrating the issue and file an issue
- [ ] If no other solution is found, refactor the app to make pop() optional and use a direct link as a fallback
```

**Comment by kevmoo** [comment]
Can we label this `p3-major`? This is REALLY bad.
